server:
  port: 2224
  servlet:
    context-path: /api/aws-s3

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

aws-s3-kafka:
  topic-name:
    s3-car: s3_car_topic
  aws:
    s3:
      bucket-name: petproject-cars-s3-bucket-2021
      credentials:
        region: eu-north-1
        access-key:
        secret-key: 
  profile:
    cron: '* 0/30 * * * *'